version: '3'
services:
  user-service:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_DB_URL=mongodb://db:27017/userService
    ports:
      - 3000:3000
    depends_on: 
      - db
  db:
    build: 
      context: .
      dockerfile: Dockerfile.db
    volumes:
      - user-db-data:/data/db
    ports:
      - 27017:27017

volumes: 
  user-db-data:
